# ### Hyprland ###
# Apps
$terminal = foot
$browser = zen-browser
$editor = ~/.local/bin/zed
$fileExplorer = thunar

# Touchpad
$touchpadDisableTyping = true
$touchpadScrollFactor = 1.0
$workspaceSwipeFingers = 4
$gestureFingers = 3
$gestureFingersMore = 4

# Blur
$blurEnabled = true
$blurSpecialWs = false
$blurPopups = true
$blurInputMethods = true
$blurSize = 8
$blurPasses = 2
$blurXray = false

# Shadow
$shadowEnabled = true
$shadowRange = 20
$shadowRenderPower = 3
$shadowColour = rgba($surfaced4)

# Gaps
$workspaceGaps = 20
$windowGapsIn = 5
$windowGapsOut = 10
$singleWindowGapsOut = 20

# Window styling
$windowOpacity = 0.95
$windowRounding = 15

$windowBorderSize = 1
$windowGapsIn = 4
$windowGapsOut = 13
$singleWindowGapsOut = 13

# Window styling
$windowOpacity = 0.90
$windowRounding = 15

$windowBorderSize = 2
$activeWindowBorderColour = rgba($primarye6)
$inactiveWindowBorderColour = rgba($onSurfaceVariant11)

# Misc
$volumeStep = 5  # In percent
$cursorTheme = sweet-cursors
$cursorSize = 24


# ### Keybinds ###
# Workspaces
$kbMoveWinToWs = Super+Alt
$kbMoveWinToWsGroup = Ctrl+Super+Alt
$kbGoToWs = Super
$kbGoToWsGroup = Ctrl+Super

$kbNextWs = Ctrl+Super, right
$kbPrevWs = Ctrl+Super, left

$kbToggleSpecialWs = Super, W

# Window groups
$kbWindowGroupCycleNext = Alt, Tab
$kbWindowGroupCyclePrev = Shift+Alt, Tab
$kbUngroup = Super, U
$kbToggleGroup = Super, Comma

# Window actions
$kbMoveWindow = Super, Z
$kbResizeWindow = Super, X
$kbWindowPip = Super+Alt, Backslash
$kbPinWindow = Super, P
$kbWindowFullscreen = Super, F
$kbWindowBorderedFullscreen = Super+Alt, F
$kbToggleWindowFloating = Super+Alt, Space
$kbCloseWindow = Super, Q

# Special workspace toggles
$kbSystemMonitor = Ctrl+Shift, Escape
$kbMusic = Super, M
$kbCommunication = Super, D
$kbTodo = Super, R

# Apps
$kbTerminal = Super, Space
$kbBrowser = Super, B
$kbEditor = Super, C
$kbFileExplorer = Super, E

# Misc
$kbSession = Ctrl+Alt, Delete
$kbShowSidebar = Super, N
$kbClearNotifs = Ctrl+Alt, C
$kbShowPanels = Super, K
$kbLock = Super, L
$kbRestoreLock = Super+Alt, L
