# xCaptaiN09

animations {
    enabled = true

    # --- BEZIERS ---

    bezier = bounce,     0.0, 1.2, 0.2, 1.0
    bezier = elastic,    0.05, 1.25, 0.15, 1.0
    bezier = decay,      0.4,  0.0, 0.2,  1.0
    bezier = snappy,     0.2,  1.0, 0.3,  1.0

    # --- WINDOW ACTIONS ---

    animation = windowsIn,   1, 7, bounce,  slide bottom
    animation = windowsOut,  1, 6, decay,   slide bottom
    animation = windowsMove, 1, 5, elastic

    # --- FADING ---

    animation = fadeIn,  1, 4, bounce
    animation = fadeOut, 1, 6, decay
    animation = fade,    1, 5, decay

    # --- WORKSPACES & LAYERS ---

    animation = workspaces, 1, 6, bounce, slide
    animation = layers,     1, 5, bounce, slide
}
